---
# apiVersion: cert-manager.io/v1alpha2
apiVersion: cert-manager.io/v1 #for the legacy cert-manager
kind: Certificate
metadata:
  name: helloapp-api-v1-tls
  namespace: default
spec:
  secretName: helloapp-api-v1-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: helloapp-api-v1.mydomain.org
  dnsNames:
  - helloapp-api-v1.mydomain.org
  acme:
    config:
    - http01:
        ingress: helloapp-api-v1-ingress #not mandatory as same as the ingress name
      domains:
      - helloapp-api-v1.mydomain.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloapp-api-v1-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    type: helloapp-api-v1
spec:
  tls:
  - hosts:
    - helloapp-api-v1.mydomain.org
    secretName: helloapp-api-v1-tls
  rules:
  - host: helloapp-api-v1.mydomain.org
    http:
      paths:
      - backend:
          serviceName: helloapp-v1-svc
          servicePort: 80