---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    external-dns.alpha.kubernetes.io/ttl: "1m"
  labels:
    type: hello-app
spec:
  rules:
  - host: $INGRESS_HOSTNAME
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: helloapp-svc
            port:
              number: 80